spring.datasource.url=${LOCAL_DB_URL:jdbc:postgresql://localhost:5432/json_backend}
spring.datasource.username=${LOCAL_DB_USER:postgres}
spring.datasource.password=${LOCAL_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${LOCAL_JPA_DDL_AUTO:update}
spring.jpa.show-sql=${LOCAL_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
